// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  shipId: __t.u32().primaryKey().name("ship_id"),
  battleId: __t.u32().name("battle_id"),
  fleetId: __t.u32().name("fleet_id"),
  empireId: __t.u32().name("empire_id"),
  side: __t.u8(),
});
