// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  seed: __t.u32(),
  systems: __t.u32(),
  empires: __t.u32(),
  fleetsPerEmpire: __t.u32(),
  shipsPerEmpire: __t.u32(),
  battleCount: __t.u32(),
  battleFleetsPerSide: __t.u32(),
  cohortsPerColony: __t.u32(),
  popsPerCohort: __t.u32(),
};
