// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  name: __t.string().primaryKey(),
  lastWallAt: __t.f64().name("last_wall_at"),
  nextGameAt: __t.f64().name("next_game_at"),
  calls: __t.u32(),
  rowsChanged: __t.u64().name("rows_changed"),
  lastLagMs: __t.f64().name("last_lag_ms"),
  maxLagMs: __t.f64().name("max_lag_ms"),
});
