// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Weapon,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  empireId: __t.u32().name("empire_id"),
  fleetId: __t.u32().name("fleet_id"),
  name: __t.string(),
  design: __t.string(),
  hull: __t.f32(),
  maxHull: __t.f32().name("max_hull"),
  shield: __t.f32(),
  maxShield: __t.f32().name("max_shield"),
  armor: __t.f32(),
  experience: __t.u32(),
  reactor: __t.string(),
  drive: __t.string(),
  abilities: __t.array(__t.string()),
  get weapons() {
    return __t.array(Weapon);
  },
});
