// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  systemId: __t.u32().name("system_id"),
  slot: __t.u32(),
  revision: __t.u32(),
  state: __t.string(),
  changedAt: __t.f64().name("changed_at"),
  parentId: __t.string().name("parent_id"),
  bodyJson: __t.string().name("body_json"),
});
