// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  empireId: __t.u32().name("empire_id"),
  name: __t.string(),
  systemId: __t.u32().name("system_id"),
  shipCount: __t.u32().name("ship_count"),
  battleId: __t.u32().name("battle_id"),
  fromX: __t.f32().name("from_x"),
  fromY: __t.f32().name("from_y"),
  toX: __t.f32().name("to_x"),
  toY: __t.f32().name("to_y"),
  departedAt: __t.f64().name("departed_at"),
  arrivesAt: __t.f64().name("arrives_at"),
  revision: __t.u32(),
});
