// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  navigationJson: __t.string().name("navigation_json"),
  id: __t.u32().primaryKey(),
  externalId: __t.string().name("external_id"),
  kind: __t.string(),
  lastSystemId: __t.u32().name("last_system_id"),
  route: __t.array(__t.u32()),
  hull: __t.f64(),
  maxHull: __t.f64().name("max_hull"),
  shield: __t.f64(),
});
