// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  code: __t.string(),
  hostId: __t.u32().name("host_id"),
  winnerId: __t.u32().name("winner_id"),
  capacity: __t.u32(),
  autoPaused: __t.bool().name("auto_paused"),
  migrationKey: __t.string().name("migration_key"),
});
