// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  energy: __t.f64(),
  minerals: __t.f64(),
  science: __t.f64(),
  defense: __t.f64(),
  mined: __t.bool(),
  studied: __t.bool(),
  colonyName: __t.string().name("colony_name"),
  colonyJson: __t.string().name("colony_json"),
});
