// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit baca5cdf77577ed4e3f30da48a5158189c4ea43f).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import ActivateReducer from "./activate_reducer";
import AdministerGameReducer from "./administer_game_reducer";
import CancelJobReducer from "./cancel_job_reducer";
import CancelTerraformingReducer from "./cancel_terraforming_reducer";
import ConfigureReducer from "./configure_reducer";
import FocusSystemObjectsReducer from "./focus_system_objects_reducer";
import GameCommandReducer from "./game_command_reducer";
import InitializeGameReducer from "./initialize_game_reducer";
import JoinEmpireReducer from "./join_empire_reducer";
import MergeFleetsReducer from "./merge_fleets_reducer";
import MoveFleetReducer from "./move_fleet_reducer";
import RedeemGameSeatReducer from "./redeem_game_seat_reducer";
import RenameBodyReducer from "./rename_body_reducer";
import ReserveGameSeatReducer from "./reserve_game_seat_reducer";
import SeedShipsReducer from "./seed_ships_reducer";
import SetAutomationReducer from "./set_automation_reducer";
import SetClockReducer from "./set_clock_reducer";
import SetFocusReducer from "./set_focus_reducer";
import SplitFleetReducer from "./split_fleet_reducer";
import StartJobReducer from "./start_job_reducer";
import StartTerraformingReducer from "./start_terraforming_reducer";
import WithdrawFleetReducer from "./withdraw_fleet_reducer";

// Import all procedure arg schemas
import * as SampleClockProcedure from "./sample_clock_procedure";

// Import all table schema definitions
import BattleMotionRow from "./battle_motion_table";
import BattleRosterRow from "./battle_roster_table";
import BattleVitalsRow from "./battle_vitals_table";
import ClockRow from "./clock_table";
import CrisisRow from "./crisis_table";
import DiagnosticsRow from "./diagnostics_table";
import EmpireSummaryRow from "./empire_summary_table";
import FleetShipsRow from "./fleet_ships_table";
import FocusedBattleRow from "./focused_battle_table";
import FocusedObjectSystemsRow from "./focused_object_systems_table";
import FocusedSystemObjectsRow from "./focused_system_objects_table";
import GalaxyFleetsRow from "./galaxy_fleets_table";
import GameAtlasRow from "./game_atlas_table";
import GameCrisisRow from "./game_crisis_table";
import GameFleetInfoRow from "./game_fleet_info_table";
import GameIntelRow from "./game_intel_table";
import GameLaneRow from "./game_lane_table";
import GamePlayersRow from "./game_players_table";
import GamePresenceRow from "./game_presence_table";
import GameRelationRow from "./game_relation_table";
import GameSettingsRow from "./game_settings_table";
import MyCohortsRow from "./my_cohorts_table";
import MyColoniesRow from "./my_colonies_table";
import MyCrisisPledgesRow from "./my_crisis_pledges_table";
import MyDecisionsRow from "./my_decisions_table";
import MyEmpireRow from "./my_empire_table";
import MyGameEventsRow from "./my_game_events_table";
import MyGameOffersRow from "./my_game_offers_table";
import MyGamePlayerRow from "./my_game_player_table";
import MyJobsRow from "./my_jobs_table";
import MyPlanetColoniesRow from "./my_planet_colonies_table";
import MyResearchRow from "./my_research_table";
import MySituationsRow from "./my_situations_table";
import MyTerraformProjectsRow from "./my_terraform_projects_table";
import MyTradeRow from "./my_trade_table";
import MyTreatiesRow from "./my_treaties_table";
import ScenarioRow from "./scenario_table";
import StarRow from "./star_table";
import VisibleBattleSummariesRow from "./visible_battle_summaries_table";
import VisibleGameSitesRow from "./visible_game_sites_table";
import VisibleStellarWeatherRow from "./visible_stellar_weather_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  clock: __table({
    name: 'clock',
    indexes: [
      { accessor: 'id', name: 'clock_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'clock_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ClockRow),
  crisis: __table({
    name: 'crisis',
    indexes: [
      { accessor: 'id', name: 'crisis_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'crisis_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CrisisRow),
  empireSummary: __table({
    name: 'empire_summary',
    indexes: [
      { accessor: 'id', name: 'empire_summary_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'empire_summary_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EmpireSummaryRow),
  gameCrisis: __table({
    name: 'game_crisis',
    indexes: [
      { accessor: 'id', name: 'game_crisis_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'game_crisis_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameCrisisRow),
  gameLane: __table({
    name: 'game_lane',
    indexes: [
      { accessor: 'a', name: 'game_lane_a_idx_btree', algorithm: 'btree', columns: [
        'a',
      ] },
      { accessor: 'b', name: 'game_lane_b_idx_btree', algorithm: 'btree', columns: [
        'b',
      ] },
      { accessor: 'id', name: 'game_lane_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'game_lane_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameLaneRow),
  gamePresence: __table({
    name: 'game_presence',
    indexes: [
      { accessor: 'id', name: 'game_presence_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'game_presence_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GamePresenceRow),
  gameRelation: __table({
    name: 'game_relation',
    indexes: [
      { accessor: 'id', name: 'game_relation_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'game_relation_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameRelationRow),
  gameSettings: __table({
    name: 'game_settings',
    indexes: [
      { accessor: 'id', name: 'game_settings_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'game_settings_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameSettingsRow),
  scenario: __table({
    name: 'scenario',
    indexes: [
      { accessor: 'id', name: 'scenario_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'scenario_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ScenarioRow),
  star: __table({
    name: 'star',
    indexes: [
      { accessor: 'id', name: 'star_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'ownerId', name: 'star_owner_id_idx_btree', algorithm: 'btree', columns: [
        'ownerId',
      ] },
    ],
    constraints: [
      { name: 'star_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, StarRow),
  battleMotion: __table({
    name: 'battle_motion',
    indexes: [
    ],
    constraints: [
    ],
  }, BattleMotionRow),
  battleRoster: __table({
    name: 'battle_roster',
    indexes: [
    ],
    constraints: [
    ],
  }, BattleRosterRow),
  battleVitals: __table({
    name: 'battle_vitals',
    indexes: [
    ],
    constraints: [
    ],
  }, BattleVitalsRow),
  diagnostics: __table({
    name: 'diagnostics',
    indexes: [
    ],
    constraints: [
    ],
  }, DiagnosticsRow),
  fleetShips: __table({
    name: 'fleet_ships',
    indexes: [
    ],
    constraints: [
    ],
  }, FleetShipsRow),
  focusedBattle: __table({
    name: 'focused_battle',
    indexes: [
    ],
    constraints: [
    ],
  }, FocusedBattleRow),
  focusedObjectSystems: __table({
    name: 'focused_object_systems',
    indexes: [
    ],
    constraints: [
    ],
  }, FocusedObjectSystemsRow),
  focusedSystemObjects: __table({
    name: 'focused_system_objects',
    indexes: [
    ],
    constraints: [
    ],
  }, FocusedSystemObjectsRow),
  galaxyFleets: __table({
    name: 'galaxy_fleets',
    indexes: [
    ],
    constraints: [
    ],
  }, GalaxyFleetsRow),
  gameAtlas: __table({
    name: 'game_atlas',
    indexes: [
    ],
    constraints: [
    ],
  }, GameAtlasRow),
  gameFleetInfo: __table({
    name: 'game_fleet_info',
    indexes: [
    ],
    constraints: [
    ],
  }, GameFleetInfoRow),
  gameIntel: __table({
    name: 'game_intel',
    indexes: [
    ],
    constraints: [
    ],
  }, GameIntelRow),
  gamePlayers: __table({
    name: 'game_players',
    indexes: [
    ],
    constraints: [
    ],
  }, GamePlayersRow),
  myCohorts: __table({
    name: 'my_cohorts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCohortsRow),
  myColonies: __table({
    name: 'my_colonies',
    indexes: [
    ],
    constraints: [
    ],
  }, MyColoniesRow),
  myCrisisPledges: __table({
    name: 'my_crisis_pledges',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCrisisPledgesRow),
  myDecisions: __table({
    name: 'my_decisions',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDecisionsRow),
  myEmpire: __table({
    name: 'my_empire',
    indexes: [
    ],
    constraints: [
    ],
  }, MyEmpireRow),
  myGameEvents: __table({
    name: 'my_game_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyGameEventsRow),
  myGameOffers: __table({
    name: 'my_game_offers',
    indexes: [
    ],
    constraints: [
    ],
  }, MyGameOffersRow),
  myGamePlayer: __table({
    name: 'my_game_player',
    indexes: [
    ],
    constraints: [
    ],
  }, MyGamePlayerRow),
  myJobs: __table({
    name: 'my_jobs',
    indexes: [
    ],
    constraints: [
    ],
  }, MyJobsRow),
  myPlanetColonies: __table({
    name: 'my_planet_colonies',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPlanetColoniesRow),
  myResearch: __table({
    name: 'my_research',
    indexes: [
    ],
    constraints: [
    ],
  }, MyResearchRow),
  mySituations: __table({
    name: 'my_situations',
    indexes: [
    ],
    constraints: [
    ],
  }, MySituationsRow),
  myTerraformProjects: __table({
    name: 'my_terraform_projects',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTerraformProjectsRow),
  myTrade: __table({
    name: 'my_trade',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTradeRow),
  myTreaties: __table({
    name: 'my_treaties',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTreatiesRow),
  visibleBattleSummaries: __table({
    name: 'visible_battle_summaries',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleBattleSummariesRow),
  visibleGameSites: __table({
    name: 'visible_game_sites',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleGameSitesRow),
  visibleStellarWeather: __table({
    name: 'visible_stellar_weather',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleStellarWeatherRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("activate", ActivateReducer),
  __reducerSchema("administer_game", AdministerGameReducer),
  __reducerSchema("cancel_job", CancelJobReducer),
  __reducerSchema("cancel_terraforming", CancelTerraformingReducer),
  __reducerSchema("configure", ConfigureReducer),
  __reducerSchema("focus_system_objects", FocusSystemObjectsReducer),
  __reducerSchema("game_command", GameCommandReducer),
  __reducerSchema("initialize_game", InitializeGameReducer),
  __reducerSchema("join_empire", JoinEmpireReducer),
  __reducerSchema("merge_fleets", MergeFleetsReducer),
  __reducerSchema("move_fleet", MoveFleetReducer),
  __reducerSchema("redeem_game_seat", RedeemGameSeatReducer),
  __reducerSchema("rename_body", RenameBodyReducer),
  __reducerSchema("reserve_game_seat", ReserveGameSeatReducer),
  __reducerSchema("seed_ships", SeedShipsReducer),
  __reducerSchema("set_automation", SetAutomationReducer),
  __reducerSchema("set_clock", SetClockReducer),
  __reducerSchema("set_focus", SetFocusReducer),
  __reducerSchema("split_fleet", SplitFleetReducer),
  __reducerSchema("start_job", StartJobReducer),
  __reducerSchema("start_terraforming", StartTerraformingReducer),
  __reducerSchema("withdraw_fleet", WithdrawFleetReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("sample_clock", SampleClockProcedure.params, SampleClockProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

