// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  colonyId: __t.u32().name("colony_id"),
  empireId: __t.u32().name("empire_id"),
  species: __t.string(),
  job: __t.string(),
  count: __t.u32(),
  productivity: __t.f32(),
  happiness: __t.f32(),
});
