// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MonthlyProduction,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  empireId: __t.u32().name("empire_id"),
  population: __t.u32(),
  get monthlyProduction() {
    return MonthlyProduction.name("monthly_production");
  },
  lastProducedAt: __t.f64().name("last_produced_at"),
});
