// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  energy: __t.f64(),
  minerals: __t.f64(),
  data: __t.f64(),
  unity: __t.f64(),
  productionModifier: __t.f64().name("production_modifier"),
  researchLevel: __t.u32().name("research_level"),
  ai: __t.bool(),
  nextDecisionTick: __t.u64().name("next_decision_tick"),
  aiCursor: __t.u32().name("ai_cursor"),
  seededShips: __t.u32().name("seeded_ships"),
});
