// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DiplomaticResources,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  get give() {
    return DiplomaticResources;
  },
  get receive() {
    return DiplomaticResources;
  },
  createdAt: __t.f64().name("created_at"),
});
