// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  empireId: __t.u32().name("empire_id"),
  kind: __t.string(),
  topic: __t.string(),
  targetId: __t.u32().name("target_id"),
  workDone: __t.f64().name("work_done"),
  workTotal: __t.f64().name("work_total"),
  rate: __t.f64(),
  updatedAt: __t.f64().name("updated_at"),
  dueTick: __t.u64().name("due_tick"),
  status: __t.string(),
});
