// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  systemId: __t.u32().name("system_id"),
  empireId: __t.u32().name("empire_id"),
  from: __t.string(),
  target: __t.string(),
  startedAt: __t.f64().name("started_at"),
  finishAt: __t.f64().name("finish_at"),
  finishTick: __t.u64().name("finish_tick"),
  paidEnergy: __t.f64().name("paid_energy"),
  paidMinerals: __t.f64().name("paid_minerals"),
  paidData: __t.f64().name("paid_data"),
});
