// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  empireId: __t.u32().name("empire_id"),
  fromSystem: __t.u32().name("from_system"),
  toSystem: __t.u32().name("to_system"),
  energyPerCycle: __t.f64().name("energy_per_cycle"),
  deliveredAt: __t.f64().name("delivered_at"),
  status: __t.string(),
});
