// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  seed: __t.u32(),
  systems: __t.u32(),
  empires: __t.u32(),
  fleetsPerEmpire: __t.u32().name("fleets_per_empire"),
  shipsPerEmpire: __t.u32().name("ships_per_empire"),
  battleCount: __t.u32().name("battle_count"),
  battleFleetsPerSide: __t.u32().name("battle_fleets_per_side"),
  cohortsPerColony: __t.u32().name("cohorts_per_colony"),
  popsPerCohort: __t.u32().name("pops_per_cohort"),
  seededShips: __t.u32().name("seeded_ships"),
  phase: __t.string(),
  schemaVersion: __t.u32().name("schema_version"),
});
