// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Administrator = __t.object("Administrator", {
  id: __t.u32(),
  identity: __t.identity(),
});
export type Administrator = __Infer<typeof Administrator>;

export const AiSchedule = __t.object("AiSchedule", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type AiSchedule = __Infer<typeof AiSchedule>;

export const Arrival = __t.object("Arrival", {
  fleetId: __t.u32(),
  dueTick: __t.u64(),
});
export type Arrival = __Infer<typeof Arrival>;

export const Battle = __t.object("Battle", {
  id: __t.u32(),
  systemId: __t.u32(),
  state: __t.string(),
  attackers: __t.u32(),
  defenders: __t.u32(),
  startedAt: __t.f64(),
  simulatedAt: __t.f64(),
  step: __t.u32(),
  attackerLosses: __t.u32(),
  defenderLosses: __t.u32(),
  winnerId: __t.u32(),
});
export type Battle = __Infer<typeof Battle>;

export const BattleMotion = __t.object("BattleMotion", {});
export type BattleMotion = __Infer<typeof BattleMotion>;

export const BattleMotionProjection = __t.object("BattleMotionProjection", {
  shipId: __t.u32(),
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
});
export type BattleMotionProjection = __Infer<typeof BattleMotionProjection>;

export const BattleReport = __t.object("BattleReport", {
  id: __t.u32(),
  systemId: __t.u32(),
  attackers: __t.u32(),
  defenders: __t.u32(),
  attackerDamage: __t.f64(),
  defenderDamage: __t.f64(),
  nextPublishWallAt: __t.f64(),
  get report() {
    return BattleSummarySnapshot;
  },
});
export type BattleReport = __Infer<typeof BattleReport>;

export const BattleRoster = __t.object("BattleRoster", {});
export type BattleRoster = __Infer<typeof BattleRoster>;

export const BattleRosterProjection = __t.object("BattleRosterProjection", {
  shipId: __t.u32(),
  battleId: __t.u32(),
  fleetId: __t.u32(),
  empireId: __t.u32(),
  side: __t.u8(),
});
export type BattleRosterProjection = __Infer<typeof BattleRosterProjection>;

export const BattleSideSummary = __t.object("BattleSideSummary", {
  ships: __t.u32(),
  hull: __t.f64(),
  shield: __t.f64(),
  startingHull: __t.f64(),
  startingShield: __t.f64(),
  damageDealt: __t.f64(),
});
export type BattleSideSummary = __Infer<typeof BattleSideSummary>;

export const BattleSummarySnapshot = __t.object("BattleSummarySnapshot", {
  id: __t.u32(),
  systemId: __t.u32(),
  state: __t.string(),
  attackers: __t.u32(),
  defenders: __t.u32(),
  winnerId: __t.u32(),
  sampledAt: __t.f64(),
  startedAt: __t.f64(),
  attackerLosses: __t.u32(),
  defenderLosses: __t.u32(),
  get attacker() {
    return BattleSideSummary;
  },
  get defender() {
    return BattleSideSummary;
  },
});
export type BattleSummarySnapshot = __Infer<typeof BattleSummarySnapshot>;

export const BattleVitals = __t.object("BattleVitals", {});
export type BattleVitals = __Infer<typeof BattleVitals>;

export const BattleVitalsProjection = __t.object("BattleVitalsProjection", {
  shipId: __t.u32(),
  targetId: __t.u32(),
  hull: __t.f32(),
  shield: __t.f32(),
  nextFireAt: __t.f64(),
});
export type BattleVitalsProjection = __Infer<typeof BattleVitalsProjection>;

export const Clock = __t.object("Clock", {
  id: __t.u32(),
  gameTime: __t.f64(),
  wallTime: __t.f64(),
  speed: __t.f64(),
  paused: __t.bool(),
});
export type Clock = __Infer<typeof Clock>;

export const ClockSample = __t.object("ClockSample", {
  gameTime: __t.f64(),
  wallTime: __t.f64(),
  speed: __t.f64(),
  paused: __t.bool(),
  serverTime: __t.f64(),
});
export type ClockSample = __Infer<typeof ClockSample>;

export const Cohort = __t.object("Cohort", {
  id: __t.u32(),
  colonyId: __t.u32(),
  empireId: __t.u32(),
  species: __t.string(),
  job: __t.string(),
  count: __t.u32(),
  productivity: __t.f32(),
  happiness: __t.f32(),
});
export type Cohort = __Infer<typeof Cohort>;

export const Colony = __t.object("Colony", {
  id: __t.u32(),
  empireId: __t.u32(),
  population: __t.u32(),
  get monthlyProduction() {
    return MonthlyProduction;
  },
  lastProducedAt: __t.f64(),
});
export type Colony = __Infer<typeof Colony>;

export const CombatSchedule = __t.object("CombatSchedule", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CombatSchedule = __Infer<typeof CombatSchedule>;

export const CommandQuota = __t.object("CommandQuota", {
  identity: __t.identity(),
  windowAt: __t.f64(),
  calls: __t.u32(),
});
export type CommandQuota = __Infer<typeof CommandQuota>;

export const Crisis = __t.object("Crisis", {
  id: __t.u32(),
  systemId: __t.u32(),
  phase: __t.string(),
  nextPhaseAt: __t.f64(),
});
export type Crisis = __Infer<typeof Crisis>;

export const Decision = __t.object("Decision", {
  id: __t.u32(),
  empireId: __t.u32(),
  kind: __t.string(),
  phase: __t.string(),
  deadlineAt: __t.f64(),
  outcome: __t.string(),
});
export type Decision = __Infer<typeof Decision>;

export const Diagnostics = __t.object("Diagnostics", {});
export type Diagnostics = __Infer<typeof Diagnostics>;

export const DiplomaticResources = __t.object("DiplomaticResources", {
  energy: __t.f64(),
  minerals: __t.f64(),
  data: __t.f64(),
  unity: __t.f64(),
});
export type DiplomaticResources = __Infer<typeof DiplomaticResources>;

export const EconomySchedule = __t.object("EconomySchedule", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type EconomySchedule = __Infer<typeof EconomySchedule>;

export const Empire = __t.object("Empire", {
  id: __t.u32(),
  energy: __t.f64(),
  minerals: __t.f64(),
  data: __t.f64(),
  unity: __t.f64(),
  productionModifier: __t.f64(),
  researchLevel: __t.u32(),
  ai: __t.bool(),
  nextDecisionTick: __t.u64(),
  aiCursor: __t.u32(),
  seededShips: __t.u32(),
});
export type Empire = __Infer<typeof Empire>;

export const EmpireSummary = __t.object("EmpireSummary", {
  id: __t.u32(),
  name: __t.string(),
  color: __t.u32(),
  ai: __t.bool(),
});
export type EmpireSummary = __Infer<typeof EmpireSummary>;

export const Fleet = __t.object("Fleet", {
  id: __t.u32(),
  empireId: __t.u32(),
  name: __t.string(),
  systemId: __t.u32(),
  shipCount: __t.u32(),
  formation: __t.string(),
  order: __t.string(),
  battleId: __t.u32(),
  route: __t.array(__t.u32()),
  fromX: __t.f32(),
  fromY: __t.f32(),
  toX: __t.f32(),
  toY: __t.f32(),
  departedAt: __t.f64(),
  arrivesAt: __t.f64(),
  speed: __t.f32(),
  revision: __t.u32(),
});
export type Fleet = __Infer<typeof Fleet>;

export const FleetOverview = __t.object("FleetOverview", {
  id: __t.u32(),
  empireId: __t.u32(),
  name: __t.string(),
  systemId: __t.u32(),
  shipCount: __t.u32(),
  battleId: __t.u32(),
  fromX: __t.f32(),
  fromY: __t.f32(),
  toX: __t.f32(),
  toY: __t.f32(),
  departedAt: __t.f64(),
  arrivesAt: __t.f64(),
  revision: __t.u32(),
});
export type FleetOverview = __Infer<typeof FleetOverview>;

export const FleetShips = __t.object("FleetShips", {});
export type FleetShips = __Infer<typeof FleetShips>;

export const Focus = __t.object("Focus", {
  identity: __t.identity(),
  fleetId: __t.u32(),
  battleId: __t.u32(),
});
export type Focus = __Infer<typeof Focus>;

export const FocusedBattle = __t.object("FocusedBattle", {});
export type FocusedBattle = __Infer<typeof FocusedBattle>;

export const FocusedObjectSystems = __t.object("FocusedObjectSystems", {});
export type FocusedObjectSystems = __Infer<typeof FocusedObjectSystems>;

export const FocusedSystemObjects = __t.object("FocusedSystemObjects", {});
export type FocusedSystemObjects = __Infer<typeof FocusedSystemObjects>;

export const GalaxyFleets = __t.object("GalaxyFleets", {});
export type GalaxyFleets = __Infer<typeof GalaxyFleets>;

export const GameAtlas = __t.object("GameAtlas", {});
export type GameAtlas = __Infer<typeof GameAtlas>;

export const GameAtlasRow = __t.object("GameAtlasRow", {
  id: __t.u32(),
  externalId: __t.string(),
  color: __t.string(),
  starClass: __t.string(),
  planet: __t.string(),
  anomaly: __t.bool(),
});
export type GameAtlasRow = __Infer<typeof GameAtlasRow>;

export const GameConnection = __t.object("GameConnection", {
  id: __t.string(),
  identity: __t.identity(),
  empireId: __t.u32(),
});
export type GameConnection = __Infer<typeof GameConnection>;

export const GameCrisis = __t.object("GameCrisis", {
  id: __t.u32(),
  kind: __t.string(),
  target: __t.u32(),
  progress: __t.u32(),
  startedAt: __t.f64(),
  endedAt: __t.f64(),
});
export type GameCrisis = __Infer<typeof GameCrisis>;

export const GameCrisisPledge = __t.object("GameCrisisPledge", {
  id: __t.string(),
  crisisId: __t.u32(),
  empireId: __t.u32(),
  contributions: __t.u32(),
  shielded: __t.bool(),
});
export type GameCrisisPledge = __Infer<typeof GameCrisisPledge>;

export const GameDamaged = __t.object("GameDamaged", {
  id: __t.u32(),
  fleetId: __t.u32(),
});
export type GameDamaged = __Infer<typeof GameDamaged>;

export const GameEvent = __t.object("GameEvent", {
  id: __t.u32(),
  empireId: __t.u32(),
  tick: __t.f64(),
  text: __t.string(),
  tone: __t.string(),
});
export type GameEvent = __Infer<typeof GameEvent>;

export const GameEventDirector = __t.object("GameEventDirector", {
  id: __t.u32(),
  stateJson: __t.string(),
});
export type GameEventDirector = __Infer<typeof GameEventDirector>;

export const GameFleet = __t.object("GameFleet", {
  id: __t.u32(),
  externalId: __t.string(),
  kind: __t.string(),
  lastSystemId: __t.u32(),
  retreatUntil: __t.f64(),
});
export type GameFleet = __Infer<typeof GameFleet>;

export const GameFleetCondition = __t.object("GameFleetCondition", {
  id: __t.u32(),
  hull: __t.f64(),
  maxHull: __t.f64(),
  shield: __t.f64(),
});
export type GameFleetCondition = __Infer<typeof GameFleetCondition>;

export const GameFleetInfo = __t.object("GameFleetInfo", {});
export type GameFleetInfo = __Infer<typeof GameFleetInfo>;

export const GameFleetInfoRow = __t.object("GameFleetInfoRow", {
  navigationJson: __t.string(),
  id: __t.u32(),
  externalId: __t.string(),
  kind: __t.string(),
  lastSystemId: __t.u32(),
  route: __t.array(__t.u32()),
  hull: __t.f64(),
  maxHull: __t.f64(),
  shield: __t.f64(),
});
export type GameFleetInfoRow = __Infer<typeof GameFleetInfoRow>;

export const GameIncome = __t.object("GameIncome", {
  id: __t.u32(),
  producedAt: __t.f64(),
});
export type GameIncome = __Infer<typeof GameIncome>;

export const GameIntel = __t.object("GameIntel", {});
export type GameIntel = __Infer<typeof GameIntel>;

export const GameIntelRow = __t.object("GameIntelRow", {
  id: __t.u32(),
  energy: __t.f64(),
  minerals: __t.f64(),
  data: __t.f64(),
  unity: __t.f64(),
  defense: __t.f64(),
  mined: __t.bool(),
  studied: __t.bool(),
  colonyName: __t.string(),
  colonyJson: __t.string(),
  starbaseJson: __t.string(),
  starbaseLevel: __t.u32(),
});
export type GameIntelRow = __Infer<typeof GameIntelRow>;

export const GameLane = __t.object("GameLane", {
  id: __t.u32(),
  a: __t.u32(),
  b: __t.u32(),
});
export type GameLane = __Infer<typeof GameLane>;

export const GameNavigation = __t.object("GameNavigation", {
  id: __t.u32(),
  systemId: __t.u32(),
  motionJson: __t.string(),
  ordersJson: __t.string(),
  phase: __t.string(),
  visited: __t.array(__t.u32()),
  targetSlot: __t.u32(),
  totalBodies: __t.u32(),
  dueTick: __t.u64(),
});
export type GameNavigation = __Infer<typeof GameNavigation>;

export const GameObject = __t.object("GameObject", {
  id: __t.string(),
  systemId: __t.u32(),
  slot: __t.u32(),
  revision: __t.u32(),
  state: __t.string(),
  changedAt: __t.f64(),
  parentId: __t.string(),
  bodyJson: __t.string(),
});
export type GameObject = __Infer<typeof GameObject>;

export const GameObjectCatalog = __t.object("GameObjectCatalog", {
  id: __t.u32(),
  nextSlot: __t.u32(),
  mainObjectId: __t.string(),
});
export type GameObjectCatalog = __Infer<typeof GameObjectCatalog>;

export const GameObjectFocus = __t.object("GameObjectFocus", {
  id: __t.string(),
  identity: __t.identity(),
  systemId: __t.u32(),
});
export type GameObjectFocus = __Infer<typeof GameObjectFocus>;

export const GameOffer = __t.object("GameOffer", {
  id: __t.u32(),
  get give() {
    return DiplomaticResources;
  },
  get receive() {
    return DiplomaticResources;
  },
  createdAt: __t.f64(),
});
export type GameOffer = __Infer<typeof GameOffer>;

export const GamePlanetColony = __t.object("GamePlanetColony", {
  id: __t.string(),
  systemId: __t.u32(),
  empireId: __t.u32(),
  colonyJson: __t.string(),
  growthAt: __t.f64(),
  lastProducedAt: __t.f64(),
});
export type GamePlanetColony = __Infer<typeof GamePlanetColony>;

export const GamePlayer = __t.object("GamePlayer", {
  id: __t.u32(),
  externalId: __t.string(),
  homeId: __t.u32(),
  techs: __t.array(__t.string()),
  surveyed: __t.array(__t.u32()),
  discovered: __t.array(__t.u32()),
  empireJson: __t.string(),
  joinedAt: __t.f64(),
});
export type GamePlayer = __Infer<typeof GamePlayer>;

export const GamePlayerSummary = __t.object("GamePlayerSummary", {
  id: __t.u32(),
  externalId: __t.string(),
  homeId: __t.u32(),
  colonies: __t.u32(),
  flagJson: __t.string(),
  shipSet: __t.string(),
});
export type GamePlayerSummary = __Infer<typeof GamePlayerSummary>;

export const GamePlayers = __t.object("GamePlayers", {});
export type GamePlayers = __Infer<typeof GamePlayers>;

export const GamePresence = __t.object("GamePresence", {
  id: __t.u32(),
  online: __t.bool(),
});
export type GamePresence = __Infer<typeof GamePresence>;

export const GameRelation = __t.object("GameRelation", {
  id: __t.string(),
  empireA: __t.u32(),
  empireB: __t.u32(),
  state: __t.string(),
  truceUntil: __t.f64(),
  changedAt: __t.f64(),
});
export type GameRelation = __Infer<typeof GameRelation>;

export const GameResearch = __t.object("GameResearch", {
  id: __t.u32(),
  programJson: __t.string(),
  updatedAt: __t.f64(),
});
export type GameResearch = __Infer<typeof GameResearch>;

export const GameSettings = __t.object("GameSettings", {
  id: __t.u32(),
  code: __t.string(),
  hostId: __t.u32(),
  winnerId: __t.u32(),
  capacity: __t.u32(),
  autoPaused: __t.bool(),
  creationKey: __t.string(),
});
export type GameSettings = __Infer<typeof GameSettings>;

export const GameSite = __t.object("GameSite", {
  id: __t.string(),
  systemId: __t.u32(),
  bodySlot: __t.u32(),
  empireId: __t.u32(),
  facility: __t.string(),
  level: __t.u32(),
  building: __t.bool(),
  startedAt: __t.f64(),
  finishAt: __t.f64(),
  finishTick: __t.u64(),
  paidEnergy: __t.f64(),
  paidMinerals: __t.f64(),
  lastProducedAt: __t.f64(),
});
export type GameSite = __Infer<typeof GameSite>;

export const GameSituation = __t.object("GameSituation", {
  id: __t.u32(),
  empireId: __t.u32(),
  definitionId: __t.string(),
  sourceKey: __t.string(),
  systemId: __t.u32(),
  stateJson: __t.string(),
  nextTick: __t.u64(),
});
export type GameSituation = __Infer<typeof GameSituation>;

export const GameStellarWeather = __t.object("GameStellarWeather", {
  id: __t.u32(),
  objectId: __t.string(),
  phase: __t.string(),
  discoveredAt: __t.f64(),
  startsAt: __t.f64(),
  endsAt: __t.f64(),
  nextTick: __t.u64(),
});
export type GameStellarWeather = __Infer<typeof GameStellarWeather>;

export const GameSystem = __t.object("GameSystem", {
  id: __t.u32(),
  externalId: __t.string(),
  color: __t.string(),
  starClass: __t.string(),
  planet: __t.string(),
  energy: __t.f64(),
  minerals: __t.f64(),
  data: __t.f64(),
  unity: __t.f64(),
  defense: __t.f64(),
  mined: __t.bool(),
  anomaly: __t.bool(),
  studied: __t.bool(),
  colonyName: __t.string(),
  colonyJson: __t.string(),
  starbaseJson: __t.string(),
  starbaseRevision: __t.u32(),
  growthAt: __t.f64(),
});
export type GameSystem = __Infer<typeof GameSystem>;

export const GameTerraform = __t.object("GameTerraform", {
  id: __t.string(),
  systemId: __t.u32(),
  empireId: __t.u32(),
  from: __t.string(),
  target: __t.string(),
  startedAt: __t.f64(),
  finishAt: __t.f64(),
  workTotal: __t.f64(),
  workDone: __t.f64(),
  updatedAt: __t.f64(),
  rate: __t.f64(),
  finishTick: __t.u64(),
  paidEnergy: __t.f64(),
  paidMinerals: __t.f64(),
  paidData: __t.f64(),
});
export type GameTerraform = __Infer<typeof GameTerraform>;

export const GameTicket = __t.object("GameTicket", {
  ticket: __t.string(),
  empireId: __t.u32(),
  expiresAt: __t.f64(),
});
export type GameTicket = __Infer<typeof GameTicket>;

export const Job = __t.object("Job", {
  id: __t.u32(),
  empireId: __t.u32(),
  kind: __t.string(),
  topic: __t.string(),
  targetId: __t.u32(),
  workDone: __t.f64(),
  workTotal: __t.f64(),
  rate: __t.f64(),
  updatedAt: __t.f64(),
  dueTick: __t.u64(),
  status: __t.string(),
});
export type Job = __Infer<typeof Job>;

export const Membership = __t.object("Membership", {
  identity: __t.identity(),
  empireId: __t.u32(),
});
export type Membership = __Infer<typeof Membership>;

export const MonthlyProduction = __t.object("MonthlyProduction", {
  energy: __t.f64(),
  minerals: __t.f64(),
  data: __t.f64(),
  unity: __t.f64(),
});
export type MonthlyProduction = __Infer<typeof MonthlyProduction>;

export const MyCohorts = __t.object("MyCohorts", {});
export type MyCohorts = __Infer<typeof MyCohorts>;

export const MyColonies = __t.object("MyColonies", {});
export type MyColonies = __Infer<typeof MyColonies>;

export const MyCrisisPledges = __t.object("MyCrisisPledges", {});
export type MyCrisisPledges = __Infer<typeof MyCrisisPledges>;

export const MyDecisions = __t.object("MyDecisions", {});
export type MyDecisions = __Infer<typeof MyDecisions>;

export const MyEmpire = __t.object("MyEmpire", {});
export type MyEmpire = __Infer<typeof MyEmpire>;

export const MyGameEvents = __t.object("MyGameEvents", {});
export type MyGameEvents = __Infer<typeof MyGameEvents>;

export const MyGameOffers = __t.object("MyGameOffers", {});
export type MyGameOffers = __Infer<typeof MyGameOffers>;

export const MyGamePlayer = __t.object("MyGamePlayer", {});
export type MyGamePlayer = __Infer<typeof MyGamePlayer>;

export const MyJobs = __t.object("MyJobs", {});
export type MyJobs = __Infer<typeof MyJobs>;

export const MyPlanetColonies = __t.object("MyPlanetColonies", {});
export type MyPlanetColonies = __Infer<typeof MyPlanetColonies>;

export const MyResearch = __t.object("MyResearch", {});
export type MyResearch = __Infer<typeof MyResearch>;

export const MySituations = __t.object("MySituations", {});
export type MySituations = __Infer<typeof MySituations>;

export const MyTerraformProjects = __t.object("MyTerraformProjects", {});
export type MyTerraformProjects = __Infer<typeof MyTerraformProjects>;

export const MyTrade = __t.object("MyTrade", {});
export type MyTrade = __Infer<typeof MyTrade>;

export const MyTreaties = __t.object("MyTreaties", {});
export type MyTreaties = __Infer<typeof MyTreaties>;

export const Participant = __t.object("Participant", {
  shipId: __t.u32(),
  battleId: __t.u32(),
  fleetId: __t.u32(),
  empireId: __t.u32(),
  side: __t.u32(),
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  targetId: __t.u32(),
  hull: __t.f32(),
  shield: __t.f32(),
  armor: __t.f32(),
  damage: __t.f32(),
  cooldown: __t.f32(),
  nextFireAt: __t.f64(),
  maneuver: __t.string(),
});
export type Participant = __Infer<typeof Participant>;

export const PlanetColonyRow = __t.object("PlanetColonyRow", {
  id: __t.string(),
  systemId: __t.u32(),
  bodySlot: __t.u32(),
  bodyJson: __t.string(),
  colonyJson: __t.string(),
});
export type PlanetColonyRow = __Infer<typeof PlanetColonyRow>;

export const ResearchSnapshot = __t.object("ResearchSnapshot", {
  id: __t.u32(),
  programJson: __t.string(),
  updatedAt: __t.f64(),
  compute: __t.f64(),
});
export type ResearchSnapshot = __Infer<typeof ResearchSnapshot>;

export const Runtime = __t.object("Runtime", {
  name: __t.string(),
  lastWallAt: __t.f64(),
  nextGameAt: __t.f64(),
  calls: __t.u32(),
  rowsChanged: __t.u64(),
  lastLagMs: __t.f64(),
  maxLagMs: __t.f64(),
});
export type Runtime = __Infer<typeof Runtime>;

export const Scenario = __t.object("Scenario", {
  id: __t.u32(),
  seed: __t.u32(),
  systems: __t.u32(),
  empires: __t.u32(),
  fleetsPerEmpire: __t.u32(),
  shipsPerEmpire: __t.u32(),
  battleCount: __t.u32(),
  battleFleetsPerSide: __t.u32(),
  cohortsPerColony: __t.u32(),
  popsPerCohort: __t.u32(),
  seededShips: __t.u32(),
  phase: __t.string(),
  schemaVersion: __t.u32(),
});
export type Scenario = __Infer<typeof Scenario>;

export const Ship = __t.object("Ship", {
  id: __t.u32(),
  empireId: __t.u32(),
  fleetId: __t.u32(),
  name: __t.string(),
  design: __t.string(),
  hull: __t.f32(),
  maxHull: __t.f32(),
  shield: __t.f32(),
  maxShield: __t.f32(),
  armor: __t.f32(),
  experience: __t.u32(),
  reactor: __t.string(),
  drive: __t.string(),
  abilities: __t.array(__t.string()),
  get weapons() {
    return __t.array(Weapon);
  },
});
export type Ship = __Infer<typeof Ship>;

export const SituationSnapshot = __t.object("SituationSnapshot", {
  id: __t.u32(),
  definitionId: __t.string(),
  systemId: __t.u32(),
  stateJson: __t.string(),
  availableChoices: __t.array(__t.string()),
});
export type SituationSnapshot = __Infer<typeof SituationSnapshot>;

export const Star = __t.object("Star", {
  id: __t.u32(),
  name: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  kind: __t.string(),
  ownerId: __t.u32(),
});
export type Star = __Infer<typeof Star>;

export const StrategicSchedule = __t.object("StrategicSchedule", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type StrategicSchedule = __Infer<typeof StrategicSchedule>;

export const Trade = __t.object("Trade", {
  id: __t.u32(),
  empireId: __t.u32(),
  fromSystem: __t.u32(),
  toSystem: __t.u32(),
  monthlyEnergy: __t.f64(),
  deliveredAt: __t.f64(),
  status: __t.string(),
});
export type Trade = __Infer<typeof Trade>;

export const Treaty = __t.object("Treaty", {
  id: __t.u32(),
  empireA: __t.u32(),
  empireB: __t.u32(),
  kind: __t.string(),
  status: __t.string(),
  expiresAt: __t.f64(),
});
export type Treaty = __Infer<typeof Treaty>;

export const VisibleBattleSummaries = __t.object("VisibleBattleSummaries", {});
export type VisibleBattleSummaries = __Infer<typeof VisibleBattleSummaries>;

export const VisibleBattleSummaryProjection = __t.object("VisibleBattleSummaryProjection", {
  id: __t.u32(),
  systemId: __t.u32(),
  state: __t.string(),
  attackers: __t.u32(),
  defenders: __t.u32(),
  winnerId: __t.u32(),
  sampledAt: __t.f64(),
  startedAt: __t.f64(),
  attackerLosses: __t.u32(),
  defenderLosses: __t.u32(),
  get attacker() {
    return BattleSideSummary;
  },
  get defender() {
    return BattleSideSummary;
  },
});
export type VisibleBattleSummaryProjection = __Infer<typeof VisibleBattleSummaryProjection>;

export const VisibleGameSites = __t.object("VisibleGameSites", {});
export type VisibleGameSites = __Infer<typeof VisibleGameSites>;

export const VisibleStellarWeather = __t.object("VisibleStellarWeather", {});
export type VisibleStellarWeather = __Infer<typeof VisibleStellarWeather>;

export const Weapon = __t.object("Weapon", {
  kind: __t.string(),
  damage: __t.f32(),
  range: __t.f32(),
  cooldown: __t.f32(),
});
export type Weapon = __Infer<typeof Weapon>;

