// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  objectId: __t.string().name("object_id"),
  phase: __t.string(),
  discoveredAt: __t.f64().name("discovered_at"),
  startsAt: __t.f64().name("starts_at"),
  endsAt: __t.f64().name("ends_at"),
  nextTick: __t.u64().name("next_tick"),
});
