// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  systemId: __t.u32().name("system_id"),
  state: __t.string(),
  attackers: __t.u32(),
  defenders: __t.u32(),
  startedAt: __t.f64().name("started_at"),
  simulatedAt: __t.f64().name("simulated_at"),
  step: __t.u32(),
  attackerLosses: __t.u32().name("attacker_losses"),
  defenderLosses: __t.u32().name("defender_losses"),
  winnerId: __t.u32().name("winner_id"),
});
