extends Node

func _ready() -> void:
	SettingsManager.set_design_variant("clean", false)
	DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_WINDOWED)
	DisplayServer.window_set_size(Vector2i(1280, 720))
	SimClock.pause_sim()
	var game: Node = load("res://scene/game/GameScene.tscn").instantiate()
	game.configure({"seed_text": "observatory-review", "star_count": 64})
	add_child(game)
	var state: GameSceneState = game.get("_state")
	await get_tree().process_frame
	while state.is_generating: await get_tree().process_frame
	SimClock.pause_sim()
	await frames()
	var shell: Control = game.get_node("CanvasLayer/GalaxyHud").get("_atlas_shell")
	assert(shell.visible and not shell.bottom.visible and not shell.drawer.visible)
	for resolution in [Vector2i(1280, 720), Vector2i(960, 540)]:
		DisplayServer.window_set_size(resolution)
		await frames()
		for category in range(4):
			shell.call("_navigate", category)
			await frames()
			assert(shell.operations.visible and shell.bottom.tab_view.current_tab == category)
			await capture("atlas_operation_%d_%d" % [resolution.x, category])
			assert(shell.operations.get_global_rect().end.x <= resolution.x + 1, "Operations width must fit")
			assert(shell.operations.get_global_rect().end.y <= resolution.y + 1, "Operations height must fit")
			await capture("atlas_operation_%d_%d" % [resolution.x, category])
		assert(shell.date.is_visible_in_tree(), "Date remains visible in compact topbar")
		assert(shell.top_band.size.y <= 64 and shell.top_band.get_global_rect().end.x <= resolution.x, "Topbar fits the window")
		assert(shell.resource_scroll.get_global_rect().end.x < shell.clock_panel.get_global_rect().position.x, "Economy and time controls never overlap")
		assert(shell.rail.size.x <= 100, "Rail must not overlap map headings")
		shell.call("_empire", "government")
		await capture("atlas_empire_%d" % resolution.x)
		assert(shell.operations.get_global_rect().end.x <= resolution.x + 1)
		shell.call("_navigate", -1)
		assert(not shell.operations.visible)
		print("PASS: mission control categories, empire and rail at ", resolution)
	var controller: Node = game.get("_scene_ui_controller")
	shell.call("_navigate", 0)
	await frames()
	var original_count: int = shell.operation_rows.get_child_count()
	shell.list_search.text = "no-such-world-123"
	shell.list_search.text_changed.emit(shell.list_search.text)
	await frames()
	assert(shell.operation_rows.get_child(0) is Label)
	shell.list_search.text = ""
	shell.list_search.text_changed.emit("")
	await frames()
	assert(shell.operation_rows.get_child_count() == original_count)
	var card: Control = shell.operation_rows.get_child(0)
	var column: Control = card.get_child(0)
	column.get_child(column.get_child_count() - 1).pressed.emit()
	await frames()
	assert(controller.is_colony_modal_visible(), "Card action must open the real colony")
	controller.close_colony_modal()
	shell.call("_empire", "research")
	await frames()
	assert(controller.is_research_modal_visible())
	controller.close_research_modal()
	shell.call("_empire", "ship_design")
	await frames()
	assert(controller.is_ship_designer_visible())
	controller.close_ship_designer_modal()
	shell.call("_open_settings")
	assert(game.get_node("SceneSystems/ViewRouter").get_system_view().preview.camera_rig.get("_input_blocked"))
	var settings: Control = shell.host.settings_overlay.get_node("AtlasSettings")
	for page in range(3):
		settings.tabs[page].pressed.emit()
		await capture("atlas_settings_960_%d" % page)
		assert(settings.pages[page].visible)
		assert(settings.panel.get_global_rect().end.x <= 961 and settings.panel.get_global_rect().end.y <= 541)
	settings.host.close_settings_requested.emit()
	assert(not shell.host.is_settings_visible())
	var router: Node = game.get_node("SceneSystems/ViewRouter")
	for record: Dictionary in state.system_records:
		if str(record.get("owner_empire_id", "")) == state.active_empire_id:
			game.get_node("SceneSystems/ViewSystem").call("_on_galaxy_view_open_system_requested", str(record["id"]))
			break
	await frames()
	assert(router.is_system_view_open())
	var system_interface: Control = router.get_system_view().get("_atlas_interface")
	system_interface.rows.get_child(0).pressed.emit()
	await frames()
	assert(router.get_system_view().get("_body_details_panel").visible)
	system_interface.index_toggle.pressed.emit()
	await frames()
	assert(system_interface.index_panel.visible and not router.get_system_view().get("_body_details_panel").visible)
	await capture("atlas_system_960")
	var system_view: SystemView = router.get_system_view()
	var field: GravityFieldMap = system_view.preview.get("_gravity_field")
	var neighbors: PackedStringArray = state.galaxy_state.get_neighbor_system_ids(system_view.get_current_system_id())
	assert(field.exit_records.size() == neighbors.size(), "One visible exit per actual hyperlane")
	for exit_record in field.exit_records:
		assert(neighbors.has(exit_record["system_id"]))
		var from: Vector3 = state.systems_by_id[system_view.get_current_system_id()]["position"]
		var to: Vector3 = state.systems_by_id[exit_record["system_id"]]["position"]
		assert(exit_record["direction"].is_equal_approx(Vector2(to.x - from.x, to.z - from.z).normalized()))
	system_interface.filter_row.get_child(3).pressed.emit()
	await frames()
	assert(system_interface.rows.get_child_count() == neighbors.size())
	if not neighbors.is_empty():
		system_interface.rows.get_child(0).pressed.emit()
		await frames()
		var point := field.to_global(field.exit_position(field.exit_records[0]) + Vector3(0, float(field.exit_records[0]["depth"]) * 0.5, 0))
		assert(system_view.preview.camera_rig.position.is_equal_approx(Vector3(point.x, 0, point.z)))
		for tag in system_interface.exit_tags:
			assert(tag.is_visible_in_tree(), "Hyperlane buttons persist after approaching an exit")
		await capture("hyperlane_focus_960")
	print("PASS: real hyperlane destinations, directions and route focus")
	shell.nav_buttons[-1].pressed.emit()
	await frames()
	assert(not router.is_system_view_open())
	print("PASS: search, colony action, research, shipyard, settings, object inspection and return to galaxy")
	SettingsManager.set_design_variant("pastel", false)
	await frames()
	assert(shell.bottom.visible and shell.drawer.visible and not shell.visible)
	assert(shell.empire_content.get_parent() == shell.empire_parent)
	SettingsManager.set_design_variant("clean", false)
	await frames()
	assert(shell.visible and shell.empire_content.get_parent() == shell.empire_stack)
	print("PASS: game navigation restores across design switches")
	get_tree().quit()

func frames() -> void:
	for frame in range(12): await get_tree().process_frame

func capture(filename: String) -> void:
	await frames()
	await RenderingServer.frame_post_draw
	get_viewport().get_texture().get_image().save_png("res://tools/screenshots/%s.png" % filename)
