extends RefCounted
class_name ForgeShipSet

## Machine/industrial ship set (dark iron, amber/ember accents), generated by
## tools/shipgen (sets/forge.py).

const SET_ID := "forge"
const GLB_PATH := "res://assets/ships/forge/forge_ships.glb"
const ALIASES := {
	"ship": "destroyer",
	"collector_station": "station",
}


static func build_mesh(visual_key: String) -> Mesh:
	return GlbShipSet.build_mesh_from_glb(GLB_PATH, visual_key, ALIASES)
