extends RefCounted
class_name GlbShipSet

## Shared loader for GLB-based ship sets generated by tools/shipgen.
## Extracts named meshes from an imported glTF scene and prepares their
## materials for MultiMesh rendering: vertex_color_use_as_albedo lets the
## per-instance COLOR (owner tint) modulate the albedo texture, exactly like
## the vertex-colored default set. Meshes and materials are cached per GLB;
## ShipSetRegistry adds its own per-set/key mesh cache on top.

static var _mesh_cache_by_glb: Dictionary = {}


static func build_mesh_from_glb(glb_path: String, visual_key: String, aliases: Dictionary = {}) -> Mesh:
	var key := str(aliases.get(visual_key, visual_key))
	var meshes := _get_meshes_for_glb(glb_path)
	if meshes.has(key):
		return meshes[key]
	return null


static func _get_meshes_for_glb(glb_path: String) -> Dictionary:
	if _mesh_cache_by_glb.has(glb_path):
		return _mesh_cache_by_glb[glb_path]
	var meshes: Dictionary = {}
	if ResourceLoader.exists(glb_path):
		var scene := load(glb_path) as PackedScene
		if scene != null:
			var root := scene.instantiate()
			var prepared_materials: Dictionary = {}
			_collect_meshes(root, meshes, prepared_materials)
			root.free()
	else:
		push_warning("GlbShipSet: missing ship set asset %s" % glb_path)
	_mesh_cache_by_glb[glb_path] = meshes
	return meshes


static func _collect_meshes(node: Node, meshes: Dictionary, prepared_materials: Dictionary) -> void:
	if node is MeshInstance3D:
		var mesh_instance := node as MeshInstance3D
		if mesh_instance.mesh != null:
			var key := _normalize_key(node.name)
			if not key.is_empty() and not meshes.has(key):
				meshes[key] = _prepare_mesh(mesh_instance.mesh, prepared_materials)
	for child in node.get_children():
		_collect_meshes(child, meshes, prepared_materials)


## Blender object names come through as node names; strip importer suffixes
## like "corvette_001" or "corvette2" duplicates down to the visual key.
static func _normalize_key(node_name: String) -> String:
	var key := node_name.to_lower().strip_edges().replace(" ", "_")
	var parts := key.rsplit("_", true, 1)
	if parts.size() == 2 and parts[1].is_valid_int():
		key = parts[0]
	return key


static func _prepare_mesh(mesh: Mesh, prepared_materials: Dictionary) -> Mesh:
	var array_mesh := mesh.duplicate() as ArrayMesh
	if array_mesh == null:
		return mesh
	for surface_index in range(array_mesh.get_surface_count()):
		var material := array_mesh.surface_get_material(surface_index)
		if material == null:
			continue
		if prepared_materials.has(material):
			array_mesh.surface_set_material(surface_index, prepared_materials[material])
			continue
		var prepared := material.duplicate() as BaseMaterial3D
		if prepared == null:
			continue
		prepared.vertex_color_use_as_albedo = true
		prepared_materials[material] = prepared
		array_mesh.surface_set_material(surface_index, prepared)
	return array_mesh
