extends RefCounted
class_name TidalShipSet

## Aquatic organic ship set (deep teal, bioluminescent glow), generated by
## tools/shipgen (sets/tidal.py).

const SET_ID := "tidal"
const GLB_PATH := "res://assets/ships/tidal/tidal_ships.glb"
const ALIASES := {
	"ship": "destroyer",
	"collector_station": "station",
}


static func build_mesh(visual_key: String) -> Mesh:
	return GlbShipSet.build_mesh_from_glb(GLB_PATH, visual_key, ALIASES)
