extends RefCounted
class_name VanguardShipSet

## Angular human military ship set (gunmetal + red accents), generated by
## tools/shipgen (sets/vanguard.py). Registered as a builtin in
## ShipSetRegistry; unknown keys fall back to the default set there.

const SET_ID := "vanguard"
const GLB_PATH := "res://assets/ships/vanguard/vanguard_ships.glb"
const ALIASES := {
	"ship": "destroyer",
	"collector_station": "station",
}


static func build_mesh(visual_key: String) -> Mesh:
	return GlbShipSet.build_mesh_from_glb(GLB_PATH, visual_key, ALIASES)
