extends RefCounted
class_name VoidShipSet

## Crystalline void ship set (obsidian + lavender glow veins), generated by
## tools/shipgen (sets/void.py).

const SET_ID := "void"
const GLB_PATH := "res://assets/ships/void/void_ships.glb"
const ALIASES := {
	"ship": "destroyer",
	"collector_station": "station",
}


static func build_mesh(visual_key: String) -> Mesh:
	return GlbShipSet.build_mesh_from_glb(GLB_PATH, visual_key, ALIASES)
