// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as SampleClockProcedure from "../sample_clock_procedure";

export type SampleClockArgs = __Infer<typeof SampleClockProcedure.params>;
export type SampleClockResult = __Infer<typeof SampleClockProcedure.returnType>;

