// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ActivateReducer from "../activate_reducer";
import CancelJobReducer from "../cancel_job_reducer";
import ConfigureReducer from "../configure_reducer";
import GameCommandReducer from "../game_command_reducer";
import InitializeBattleReportsReducer from "../initialize_battle_reports_reducer";
import InitializeDiplomacyReducer from "../initialize_diplomacy_reducer";
import InitializeGameReducer from "../initialize_game_reducer";
import InitializeStoriesReducer from "../initialize_stories_reducer";
import JoinEmpireReducer from "../join_empire_reducer";
import MergeFleetsReducer from "../merge_fleets_reducer";
import MoveFleetReducer from "../move_fleet_reducer";
import RedeemGameSeatReducer from "../redeem_game_seat_reducer";
import ReserveGameSeatReducer from "../reserve_game_seat_reducer";
import SeedShipsReducer from "../seed_ships_reducer";
import SetAutomationReducer from "../set_automation_reducer";
import SetClockReducer from "../set_clock_reducer";
import SetFocusReducer from "../set_focus_reducer";
import SplitFleetReducer from "../split_fleet_reducer";
import StartJobReducer from "../start_job_reducer";
import WithdrawFleetReducer from "../withdraw_fleet_reducer";

export type ActivateParams = __Infer<typeof ActivateReducer>;
export type CancelJobParams = __Infer<typeof CancelJobReducer>;
export type ConfigureParams = __Infer<typeof ConfigureReducer>;
export type GameCommandParams = __Infer<typeof GameCommandReducer>;
export type InitializeBattleReportsParams = __Infer<typeof InitializeBattleReportsReducer>;
export type InitializeDiplomacyParams = __Infer<typeof InitializeDiplomacyReducer>;
export type InitializeGameParams = __Infer<typeof InitializeGameReducer>;
export type InitializeStoriesParams = __Infer<typeof InitializeStoriesReducer>;
export type JoinEmpireParams = __Infer<typeof JoinEmpireReducer>;
export type MergeFleetsParams = __Infer<typeof MergeFleetsReducer>;
export type MoveFleetParams = __Infer<typeof MoveFleetReducer>;
export type RedeemGameSeatParams = __Infer<typeof RedeemGameSeatReducer>;
export type ReserveGameSeatParams = __Infer<typeof ReserveGameSeatReducer>;
export type SeedShipsParams = __Infer<typeof SeedShipsReducer>;
export type SetAutomationParams = __Infer<typeof SetAutomationReducer>;
export type SetClockParams = __Infer<typeof SetClockReducer>;
export type SetFocusParams = __Infer<typeof SetFocusReducer>;
export type SplitFleetParams = __Infer<typeof SplitFleetReducer>;
export type StartJobParams = __Infer<typeof StartJobReducer>;
export type WithdrawFleetParams = __Infer<typeof WithdrawFleetReducer>;

